### ISSUE TITLE
Something out of sync with your file names and the names in your script to copy

### ISSUE THREAD

**Issue by ReuvenSwirsky** [andrewMacmurray/phoenix-elm-scaffold#11]
It looks like you changed the names of the files in the placeholder elm sources and didn't update the script.

```
adding phoenix files 🕊 🔥
* creating lib/vartc_web/views/elm_view.ex
* creating lib/vartc_web/controllers/elm_controller.ex
* creating lib/vartc_web/templates/elm/index.html.eex
adding elm files 🌳
* creating assets/elm/Main.elm
** (RuntimeError) could not find assets/elm/Update.elm in any of the sources
    lib/mix/phoenix.ex:37: anonymous fn/4 in Mix.Phoenix.copy_from/4
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/phoenix.ex:32: Mix.Phoenix.copy_from/4
    lib/mix/tasks/phx.gen.elm.ex:69: Mix.Tasks.Phx.Gen.Elm.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

I changed phx.gen.elm.ex locally to look like this and it worked:

```
defp copy_elm_files do
    files = [
      "assets/elm/Main.elm",
      "assets/elm/State.elm",
      "assets/elm/View.elm",
      "assets/elm/Types.elm",
      "assets/js/elm-embed.js",
      "assets/elm-package.json",
      "test/elm/Main.elm",
      "test/elm/Sample.elm",
      "test/elm/elm-package.json"
    ]
    |> Enum.map(&text_file/1)
```

(The names under assets/elm were wrong)

Thanks again for your script! It saved me time on my new project.

**Comment by andrewMacmurray** [comment]
👍 closed with pr #12
