### ISSUE TITLE
Adding phoenix files failed with "Unknown Application :elm_gen"

### ISSUE THREAD

**Issue by ReuvenSwirsky** [andrewMacmurray/phoenix-elm-scaffold#4]
Not sure where :elm_gen was supposed to be defined, it only appears once in the source code

I get this error

```
[develop ≡ +1 ~4 -0 !]> mix phx.gen.elm
==> phoenix_elm_scaffold
Compiling 1 file (.ex)
Generated phoenix_elm_scaffold app
==> ui_x
adding phoenix files 🕊 🔥
** (ArgumentError) unknown application: :elm_gen
    (elixir) lib/application.ex:428: Application.app_dir/1
    (elixir) lib/application.ex:437: Application.app_dir/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/phoenix.ex:30: Mix.Phoenix.copy_from/4
    lib/mix/tasks/phx.gen.elm.ex:63: Mix.Tasks.Phx.Gen.Elm.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Here's the fix:

```
  defp copy_files(templates) do
    Mix.Phoenix.copy_from(
      [:phoenix_elm_scaffold], @src, [app_name: app_module_name()], templates
    )
  end

```

Thanks a lot; I was having trouble converting my app from 1.2 to 1.3. I'm an Erlang / Elm person and know very little about Elixir, etc.

**Comment by andrewMacmurray** [comment]
👍 
closed with pr #5
